[project]
name = "leasemanagement"
version = "0.0.1"
authors = [
    { name = "Rishi Hingad", email = "rishi.hingad@merillife.com"}
]
description = "Car and Lease Management System Monorepo"
requires-python = ">=3.10"
readme = "README.md"
dependencies = [
    "pandas>=2.2.3,<2.3",
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = [
    "leasemanagement",
    "lease_app",
    "alms_app",
    "remittance_tool",
    "approval_app",
    "car_and_lease",
    "lease_management_system",
    "lease_masters",
    "alms",
    "master",
    "crms",
    "approval"
]

[tool.setuptools.package-dir]
leasemanagement = "lease_app"
lease_app = "lease_app"
alms_app = "alms_app"
remittance_tool = "remittance/remittance_tool"
approval_app = "approval_app/approval_app"

car_and_lease = "lease_app/car_and_lease"
lease_management_system = "lease_app/lease_management_system"
lease_masters = "lease_app/lease_masters"

alms = "alms_app/alms"
master = "alms_app/master"
crms = "alms_app/crms"

approval = "approval_app/approval_app/approval"

[tool.bench.dev-dependencies]

[deploy.dependencies.apt]
packages = []

[tool.ruff]
line-length = 110
target-version = "py310"

[tool.ruff.lint]
select = [
    "F",
    "E",
    "W",
    "I",
    "UP",
    "B",
    "RUF",
]
ignore = [
    "B017",
    "B018",
    "B023",
    "B904",
    "E101",
    "E402",
    "E501",
    "E741",
    "F401",
    "F403",
    "F405",
    "F722",
    "W191",
]
typing-modules = ["frappe.types.DF"]

[tool.ruff.format]
quote-style = "double"
indent-style = "tab"
docstring-code-format = true