[project]
name = "leasemanagement"
version = "0.0.1"
description = "Property Lease Management System"
requires-python = ">=3.10"
readme = "README.md"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = [
    "leasemanagement",
    "lease_management_system",
    "lease_masters"
]

[tool.setuptools.package-dir]
leasemanagement = "leasemanagement"
lease_management_system = "leasemanagement/lease_management_system"
lease_masters = "leasemanagement/lease_masters"